#公共配置
spring:
  application:
    name: simpleShoppingMall
#默认激活的profile
  profiles:
    active: dev
#数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/simpleshoppingmall
    username: root
    password: 240016
    driver-class-name: com.mysql.cj.jdbc.Driver

#Mybatis配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: hidden        # 逻辑删除字段名
      logic-delete-value: 1            # 删除时字段的值
      logic-not-delete-value: 0        # 未删除时字段的值
  mapper-locations: classpath:/Mapper/*.xml
  type-aliases-package: com.itheima.simpleShoppingMallDemo.Model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#debug: true
